version: '3.7'

services:
  api:
    restart: always
    image: node:20.11.0-alpine
    container_name: serencare-api
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
    command: sh -c "prisma migrate dev && pnpm start:dev"
    ports:
      - ${NEST_API_PORT}:${NEST_API_PORT}
      - 9229:9229
    networks:
      my_network:
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  postgres:
    image: postgres:16-alpine
    container_name: serencare_db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      my_network:

networks:
  my_network:
volumes:
  api_db_data:
